
DELETE http://localhost:3000/person/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU1MzE5OTMwLCJleHAiOjE2NTUzMjM1MzB9.YYVGgbeYpJnzLAZw8Q6R-jLrzIrR7vqdACJx_a8gG3k