
DELETE http://localhost:3000/person/5
Content-Type: application/json
Authorization: Bearer SeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU1MzgzMTQxLCJleHAiOjE2NTUzODY3NDF9.jQNbdgkadmITa7lpsGLIF4_lrhY6oQIzNYgzn0n1EkI