export const CHAINS_NAME: {
  [chainId: string]: { name: string; currency: string };
} = {
  '1': { name: 'ETHEREUM MAINNET', currency: 'ETHER' },
  '56': { name: 'BINANCE SMART CHAIN', currency: 'BNB' },
  '137': { name: 'POLYGON MAINNET', currency: 'MATIC' },
  '43114': { name: 'AVALANCHE C-CHAIN', currency: '' },
  '65': { name: 'ETHEREUM CLASSIC MAINNET', currency: 'ETC' },
  '10': { name: 'OPTIMISM MAINNET', currency: 'ETH' },
  '42161': { name: 'ARBITRUM ONE', currency: 'ETH' },
  '250': { name: 'FANTOM OPERA', currency: 'FTM' },
  '100': { name: 'GNOSIS CHAIN', currency: 'xDAI' },
  '42220': { name: 'CELO MAINNET', currency: 'CELO' },
  '1284': { name: 'MOONBEAM', currency: 'GLMR' },
  '30': { name: 'RSK MAINNET', currency: 'RBTC' },
  // TESTNETS
  '42': { name: 'KOVAN', currency: 'ETH' },
  '69': { name: 'OPTIMISM KOVAN', currency: 'ETH' },
  '4': { name: 'RINKEBY', currency: 'ETH' },
  '421611': { name: 'ARBITRUM RINKEBY', currency: 'ETH' },
  '5': { name: 'GÖERLI', currency: 'ETH' },
  '80001': { name: 'MUMBAI', currency: 'MATIC' },
  '3': { name: 'ROPSTEN', currency: 'ETH' },
  '97': { name: 'BINANCE SMART CHAIN TESTNET', currency: 'tBNB' },
  '6': { name: 'ETHEREUM CLASSIC TESTNET', currency: 'KOT' },
};

export enum CHAINS {
  ETHEREUM = 1,
  BINANCE = 56,
  POLYGON = 137,
  AVALANCHE = 43114,
  ETHEREUM_CLASSIC = 65,
  OPTIMISM = 10,
  ARBITRUM = 42161,
  FANTOM = 250,
  GNOSIS = 100,
  CELO = 42220,
  MOONBEAM = 1284,
  RSK = 30,
  KOVAN = 42,
  OPTIMISM_KOVAN = 69,
  RINKEBY = 4,
  ARBITRUM_RINKEBY = 421611,
  GOERLI = 5,
  MUMBAI = 80001,
  ROPSTEN = 3,
  ETHEREUM_CLASSIC_TESTNET = 6,
}
